safe:        true
auto:        true
server:      false
server_port: 4000
url: http://timjames.me

production_url: http://timjames.me

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
## markdown:    kramdown
markdown:    rdiscount
permalink:   /blog/:year/:month/:day/:title/
## permalink:   pretty
highlighter: rouge
## highlighter: pygments


rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

gems:
- jekyll-sitemap
